#' @title Use the permutation method to calculate the standard deviation 
#' associated with the GSVA score obtained for each sample
#'
#' @description This function calculates GSVA score for multiple permutation 
#' sampling of the dataset to obtain the standard deviation associated with 
#' each sample.
#' 
#' @param geneLists a \code{list} containing signature gene lists. 
#'
#' @param countMatrix a normalized gene expression data 
#' \code{matrix} with rows corresponding to genes and columns to samples. The 
#' \code{matrix} has been filtered to contain only the genes present in the 
#' signature gene lists.
#' 
#' @param permRatio a \code{numeric} between 0 and 1 representing the
#' number of samples that are retained for the permutation step.
#' 
#' @param permNbr a \code{integer} bigger than or equal to 5 representing the
#' number of permutation samplings done. 
#' 
#' @returns a \code{list} containing two entries named "PERMUTATIONS" and "SD".
#' \itemize{
#'     \item The "PERMUTATIONS" entry is a \code{list} with one entry per 
#' signature name. The entry contains the \code{matrix} with all the GSVA 
#' scores for the permutations done on this signature. 
#'     \item The "SD" entry is a \code{list} with one entry per signature name. 
#' The entry contains the \code{vector} of \code{numeric} corresponding to the 
#' standard deviation calculated for each sample. The \code{NA} value is 
#' present when the standard deviation could not be calculated.
#' }
#' 
#' @examples
#'
#' ## Load signatures
#' data(signaturesDemo)
#' 
#' ## Create a list of two signatures
#' geneLists <- list()
#' geneLists[["classical"]] <- 
#'     signaturesDemo$`2018_Tiriac_PDAC_PDO_classical_signature`
#' geneLists[["basal"]] <- 
#'     signaturesDemo$`2018_Tiriac_PDAC_PDO_basal-like_signature`
#' 
#' ## Load demo normalized expected counts
#' data(expNormalCountsDemo)
#' 
#' ## Fix seed for reproducibility
#' set.seed(144)
#' 
#' ## Calculate standard deviation for each sample using permutation method
#' result <- splitTypeR:::permuteGSVA(geneLists=geneLists, 
#'     countMatrix=expNormalCountsDemo, permRatio=0.75, permNbr=20)
#' 
#' ## The output contains all the permutations and the calculated standard 
#' ## deviation in two lists called "SD" and "PERMUTATIONS"
#' 
#' ## The standard deviation of the samples for the classical signature
#' head(result[["SD"]][["classical"]])
#' 
#' ## Some of the GSVA results for the permutations related to the basal
#' ## signature
#' result[["PERMUTATIONS"]][["basal"]][5:8, 1:5]
#' 
#' @author Astrid Deschênes
#' @importFrom GSVA gsvaParam gsva
#' @importFrom stats sd
#' @encoding UTF-8
#' @keywords internal
permuteGSVA <- function(geneLists, countMatrix, permRatio, permNbr) {
    ## Number of samples used for permutation
    nb <- round(ncol(countMatrix) * permRatio)

    ## Storage for the results of the permutations
    resultBoot <- list()
    resultSD <- list()
    for (i in names(geneLists)) {
        resultBoot[[i]] <- matrix(data=NA, nrow=ncol(countMatrix), ncol=permNbr)
        rownames(resultBoot[[i]]) <- colnames(countMatrix)
    }

    ## Run GSVA on the permutations
    for (j in seq_len(permNbr)) {
        selected <- sample(x=seq_len(ncol(countMatrix)), size=nb, 
                                replace=FALSE)

        gsvaParamTmp <- gsvaParam(exprData=as.matrix(countMatrix[, selected]),
                geneSets=geneLists)

        resTmp <- gsva(param=gsvaParamTmp, verbose=FALSE)
        
        for (i in names(geneLists)) {
            resultBoot[[i]][selected, j] <- resTmp[i, ]
        }
    }

    ## Calculate standard deviation for each sample
    for (i in names(geneLists)) { 
        resultSD[[i]] <- apply(resultBoot[[i]], MARGIN=1, FUN=function(x) {
                                        sd(x, na.rm=TRUE)})
    }

    return(list("PERMUTATIONS"=resultBoot, "SD"=resultSD))
}

#' @title Sample a specific number of values from the normal distribution 
#' associated with each sample and each gene signature
#' 
#' @description This function generates a normal distribution for each 
#' sample and gene signature, using the actual GSVA score for the mean and 
#' the permutation results for the standard deviation. The function 
#' returns a user-defined number of values sampled from this distribution.
#' 
#' @param geneLists a \code{list} containing signature gene lists. 
#'
#' @param gsvaRes a \code{matrix} as generated by the GSVA function. The 
#' \code{matrix} should contain the GSVA score for all the samples (column) 
#' and the signatures (row).
#' 
#' @param gsvaSD a \code{list} containing one entry per gene signature. Each 
#' entry contains a \code{vector} of the standard deviations for each sample as 
#' calculated from the permutations. 
#' 
#' @param nbValues a \code{integer} superior or egal to 2 representing the 
#' number of values sampled. 
#' 
#' @returns a \code{list} containing one entry for each gene signature present 
#' in the \code{geneLists} object. Each entry contains a \code{matrix} with 
#' all the values sampled from the normal distribution obtained from the GSVA 
#' score (mean) and the permutations (standard deviation). The rows correspond 
#' to the samples, while the columns correspond to the number of draws. 
#'
#' @examples
#'
#' ## Required library
#' library(GSVA)
#' 
#' ## Load signatures
#' data(signaturesDemo)
#' 
#' ## Create a list of two signatures
#' geneLists <- list()
#' geneLists[["classical"]] <- 
#'     signaturesDemo$`2018_Tiriac_PDAC_PDO_classical_signature`
#' geneLists[["basal"]] <- 
#'     signaturesDemo$`2018_Tiriac_PDAC_PDO_basal-like_signature`
#' 
#' ## Load demo normalized expected counts
#' data(expNormalCountsDemo)
#' 
#' ## Fix seed for reproducibility
#' set.seed(144)
#' 
#' ## Calculate the real GSVA values
#' gsvaParameter <- gsvaParam(exprData=as.matrix(expNormalCountsDemo), 
#'      geneSets=geneLists)
#' resGSVA <- GSVA::gsva(param=gsvaParameter, verbose=FALSE)
#' 
#' ## Calculate standard deviation for each sample using the permutation method
#' permResult <- splitTypeR:::permuteGSVA(geneLists=geneLists, 
#'     countMatrix=expNormalCountsDemo, permRatio=0.75, permNbr=20)
#' 
#' ## For each signature, randomly extract values from the normal 
#' ## distribution for each sample
#' normResult <- splitTypeR:::extractFromNormalDist(geneLists=geneLists, 
#'     gsvaRes=resGSVA, gsvaSD=permResult$SD, nbValues=10)
#' ## For the classical signature, the sampled values for the first 3 patients
#' head(normResult$classical[1:3, ])
#' 
#' @author Astrid Deschênes
#' @importFrom stats sd rnorm
#' @encoding UTF-8
#' @keywords internal
extractFromNormalDist <- function(geneLists, gsvaRes, gsvaSD, nbValues) {
    
    ## Storage for the results of the drawing
    resultNorm <- list()

    ## Select a specific number of values from a normal distribution 
    ## for each sample
    for (i in names(geneLists)) {
        tmpM <- matrix(data=NA, nrow=ncol(gsvaRes), ncol=nbValues)
        rownames(tmpM) <- colnames(gsvaRes)
    
        for(name in rownames(tmpM)) {
            mean <- gsvaRes[i, name]
            sd <- unname(gsvaSD[[i]][name])
            if (!is.na(mean) && !is.na(sd)) {
                tmpM[name, ] <- rnorm(n=nbValues, mean=mean, sd=sd)
            }
        }
        resultNorm[[i]] <- tmpM
    }
    return(resultNorm)
}

#' @title Extracting the mixtures of two normal distributions for each 
#' signature
#'
#' @description This function calculates the mixtures of two normal 
#' distributions for each signature using the sampled values from the normal 
#' distribution obtained for each sample (mean=real GSVA score, 
#' standard deviation=calculated from the permutation step).
#' 
#' @param geneLists a \code{list} containing signature gene lists. 
#'
#' @param resultNorm a \code{list} containing one entry for each gene 
#' signature present in the \code{geneLists} object. Each entry contains a 
#' \code{matrix} with all the values sampled from the normal distribution 
#' obtained from the GSVA score (mean) and the permutations (standard 
#' deviation). One row of the \code{matrix} represents one sample. The columns 
#' correspond to the number of draws.
#' 
#' @returns a \code{list} containing one entry for each gene signature 
#' present in the \code{geneLists} object. Each entry contains the mixtures 
#' of two normal distributions for the signature calculated with sampled 
#' values. The entry corresponds to the object returned by the 
#' `mixtools::normalmixEM` function.
#' 
#' @examples
#'
#' ## Required library
#' library(GSVA)
#' 
#' ## Load signatures
#' data(signaturesDemo)
#' 
#' ## Create a list of two signatures
#' geneLists <- list()
#' geneLists[["classical"]] <- 
#'     signaturesDemo$`2018_Tiriac_PDAC_PDO_classical_signature`
#' geneLists[["basal"]] <- 
#'     signaturesDemo$`2018_Tiriac_PDAC_PDO_basal-like_signature`
#' 
#' ## Load demo normalized expected counts
#' data(expNormalCountsDemo)
#' 
#' ## Fix seed for reproducibility
#' set.seed(144)
#' 
#' ## Calculate GSVA scores for the signatures
#' gsvaParameter <- gsvaParam(exprData=as.matrix(expNormalCountsDemo),
#'     geneSets=geneLists)
#' resClass <- gsva(param=gsvaParameter, verbose=FALSE)
#' 
#' ## Calculate standard deviation for each sample using the permutation method
#' permResult <- splitTypeR:::permuteGSVA(geneLists=geneLists, 
#'     countMatrix=expNormalCountsDemo, permRatio=0.75, permNbr=20)
#' 
#' ## For each sample, randomly select 10 values (nbValues) from the normal 
#' ## curve where mean is the real GSVA value, and the standard deviation is 
#' ## calculated from the permutation step.
#' normResult <- splitTypeR:::extractFromNormalDist(geneLists=geneLists, 
#'     gsvaRes=resClass, gsvaSD=permResult$SD, nbValues=10)
#' 
#' ## Extracting the mixtures of two normal distributions for each signature
#' model <- splitTypeR:::normalMix(geneLists=geneLists, resultNorm=normResult)
#' 
#' ## The two means of the normal distributions for the basal signature
#' model[["basal"]]$mu
#' 
#' @author Astrid Deschênes
#' @importFrom mixtools normalmixEM
#' @encoding UTF-8
#' @keywords internal
normalMix <- function(geneLists, resultNorm) {

    ## Storage for the results of the mixed model
    resModel <- list()
    for (i in names(geneLists)) {
        ## Vector of all sampled values for the signature (NA might be present)
        allRes <- vapply(resultNorm[[i]], FUN=unlist, numeric(1))
        ## Remove NA values before calculating the normal distributions
        resModel[[i]] <- normalmixEM(allRes[!is.na(allRes)], k=2, verb=FALSE)
    }
    
    return(resModel)
}

#' @title Assign the typing for each sample and each gene signature
#'
#' @description This function assigns the typing for all samples in each 
#' signature using the 
#' two normal distributions obtained for each signature. One normal 
#' distribution is associated with the samples with the signatures while the 
#' other normal distribution is called the alternative distribution.
#' The null hypothesis is that the sample is part of the alternative 
#' distribution. At this 
#' step, the sample is considered "unclassified". The null 
#' hypothesis is rejected when the probability of the sample being part of the 
#' alternative distribution is inferior to 0.05. The sample is then considered 
#' to be part of the distribution associated to the signature and is assigned 
#' to the signature.
#' 
#' @param geneLists a \code{list} containing signature gene lists. 
#'
#' @param gsvaRes a \code{matrix} as generated by the GSVA function. The 
#' \code{matrix} should contain the GSVA score for all the samples (column) 
#' and the signatures (row).
#' 
#' @param modelMix a \code{list} containing one entry for each gene signature 
#' present in the \code{geneLists} object. Each entry contains the mixtures 
#' of two normal distributions for the signature calculated with sampled 
#' values. The entry corresponds to the object returned by the 
#' `mixtools::normalmixEM` function.
#' 
#' @returns a \code{list} containing one entry for each gene signature 
#' present in the \code{geneLists} object. Each entry contains the typing 
#' assigned to each sample for the specific signature. When the sample 
#' is not assigned to the signature, the "unclassified" value is present. 
#' When the sample is assigned to the signature, the name of the signature 
#' is present. 
#' 
#' @examples
#'
#' ## Required library
#' library(GSVA)
#' 
#' ## Load signatures
#' data(signaturesDemo)
#' 
#' ## Create a list of two signatures
#' geneLists <- list()
#' geneLists[["classical"]] <- 
#'     signaturesDemo$`2018_Tiriac_PDAC_PDO_classical_signature`
#' geneLists[["basal"]] <- 
#'     signaturesDemo$`2018_Tiriac_PDAC_PDO_basal-like_signature`
#' 
#' ## Load demo normalized expected counts
#' data(expNormalCountsDemo)
#' 
#' gsvaParameter <- gsvaParam(exprData=as.matrix(expNormalCountsDemo),
#'     geneSets=geneLists)
#' resClass <- gsva(param=gsvaParameter, verbose=FALSE)
#' 
#' ## Calculate standard deviation for each sample using the permutation method
#' permResult <- splitTypeR:::permuteGSVA(geneLists=geneLists, 
#'     countMatrix=expNormalCountsDemo, permRatio=0.75, permNbr=20)
#' 
#' ## Draw 10 values from the normal distribution for each sample (upscaling)
#' normResult <- splitTypeR:::extractFromNormalDist(geneLists=geneLists, 
#'     gsvaRes=resClass, gsvaSD=permResult$SD, nbValues=10)
#' 
#' ## Obtain the mixtures of normal distributions for each signature
#' model <- splitTypeR:::normalMix(geneLists=geneLists, resultNorm=normResult)
#' 
#' ## Obtain the assignment of each sample for each signature
#' result <- splitTypeR:::classification(geneLists=geneLists, gsvaRes=resClass, 
#'     modelMix=model)
#' ## Assignment for the classical signature
#' head(result$classical)
#' ## Assignment for the basal signature
#' head(result$basal)
#' 
#' @author Astrid Deschênes
#' @importFrom mixtools normalmixEM
#' @importFrom stats qnorm
#' @encoding UTF-8
#' @keywords internal
classification <- function(geneLists, gsvaRes, modelMix) {

    ## Storage for the results of the mixed model
    resModel <- list()
    for (i in names(geneLists)) {
        model <- modelMix[[i]]
        
        posMin <- which.min(model$mu)
        q95Min <- qnorm(p=0.95, mean=model$mu[posMin], sd=model$sigma[posMin], 
                            lower.tail=TRUE)
        resultTable <- as.data.frame(gsvaRes[i,])
        colnames(resultTable) <- c("GSVA_score")
        resultTable$assignedType <- "unclassified"
        resultTable$assignedType[resultTable$GSVA_score > q95Min] <- i
        resModel[[i]] <- resultTable
    }
    
    return(resModel)
}